name: tests
on: workflow_dispatch

jobs:
  build:
    name: build ubuntu
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: .github/test_environment.yml
          activate-environment: dustgoggles
          channels: conda-forge,defaults
          miniconda-version: latest
          channel-priority: strict
          mamba-version: "*"
          python-version: 3.9
      - name: Set up conda environment
        shell: bash -l {0}
        run: |
          python -m pip install -e .
          conda list
      - name: Run Tests
        shell: bash -l {0}
        run: pytest --cov-config=.coveragerc --cov=dustgoggles --cov-report xml:.coverage.xml
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: .coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
